### ISSUE TITLE
node_modules shouldn't be committed in git

### ISSUE THREAD

**Issue by rokaicker** [NeilAn99/nan1-ssg#1]
I believe it is best practice to add the node_modules to a .gitignore file (so that it doesn't get committed in git). 

I think the main 2 reasons for this are:

- possible conflicts in different operating systems (windows, mac, linux)
- potentially committing dev dependencies along with project dependencies

**Comment by NeilAn99** [comment]
Added a .gitignore file and removed the node_modules directory. Added instructions for users to install the required modules in the README.md file.
