### ISSUE TITLE
need to add "node" to the beginning of the command

### ISSUE THREAD

**Issue by rokaicker** [NeilAn99/nan1-ssg#3]
I believe for this project, we are required to be able to run the command without explicitly using "node" before the command. 

ie: 
`main -i hello.txt`
instead of 
`node main -i hello.txt`

**Comment by rokaicker** [comment]
https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e this is the link I used to help me with this

**Comment by NeilAn99** [comment]
Users are now able to run the command without using node (also changed command name from main to nan1-ssg).
![image](https://user-images.githubusercontent.com/54966170/189990269-9b4e4d64-42e3-43f2-a9c3-f1f6b5121fdf.png)
