### ISSUE TITLE
possibly change stylesheet colors for less eye strain

### ISSUE THREAD

**Issue by rokaicker** [NeilAn99/nan1-ssg#4]
![image](https://user-images.githubusercontent.com/97995977/189779347-c03ddd7e-b647-4843-9f5a-474a17220858.png)

In the image above I think the blueish background conflicts with the blue/ purple links. I think it might be nice to change the color scheme to make it a little easier to read.

**Comment by NeilAn99** [comment]
Changed colour scheme to make it more readable.
![image](https://user-images.githubusercontent.com/54966170/189988507-7f7972b7-f75f-4033-baf5-cd0869b82a51.png)
and
![image](https://user-images.githubusercontent.com/54966170/189988544-6bafacaf-b434-4561-9225-5cd69f3c2b77.png)
