### ISSUE TITLE
Duplicate variables

### ISSUE THREAD

**Issue by rokaicker** [NeilAn99/nan1-ssg#5]
https://github.com/NeilAn99/nan1-ssg/blob/46e96032cf07ccbec23dd515e14f2e4fd137faef/generateHTML.js#L156

In generateHTML.js Lines 156 and 157 are essentially the same variable, I think you should remove one for brevity. 

The same goes for Line 163 and Line 164.

**Comment by NeilAn99** [comment]
Removed duplicate variables.
